In [55]:
import math

r = 0.7031
N = 1107

t_statistic = r * math.sqrt(N - 2) / math.sqrt(1 - r**2)
print("t-statistic:", t_statistic)


t-statistic: 32.86798375679778


In [36]:
from scipy.stats import t

df = 1107
p_value = 2 * (1 - t.cdf(abs(t_statistic), df))
print("p-value:", p_value)


p-value: 0.0


In [7]:
import pandas as pd

In [58]:
df = pd.read_excel("Data-01.xlsx")

In [48]:
x = df['loss/bag'].to_numpy()
y = df['days'].to_numpy()

In [49]:
# Create two NumPy arrays
import numpy as np
# Calculate the mean of x and y
mean_x = np.mean(x)
mean_y = np.mean(y)

# Calculate the numerator and denominator of the correlation coefficient formula
numerator = np.sum((x - mean_x) * (y - mean_y))
denominator = np.sqrt(np.sum((x - mean_x)**2) * np.sum((y - mean_y)**2))

# Calculate the correlation coefficient
correlation_coefficient = numerator / denominator

print(f"Correlation Coefficient: {correlation_coefficient}")


Correlation Coefficient: 0.7030866930118612


In [50]:
mean_x,mean_y

(1.7490864847251233, 212.70604147880974)

In [51]:
numerator

3558.633233777766

In [52]:
denominator**2

25618205.429992165

In [53]:
from scipy.stats import t

df = 1107
alpha = 0.01

# Calculate the t-statistic for a two-tailed test
t_statistic = t.ppf(1 - alpha/2, df)
print("t-statistic:", t_statistic)


t-statistic: 2.5802778476613337


In [68]:
df['loss'].sum()

71491.70000000001

In [66]:
(df['days']*df['total_weight_out']).sum()

767506073.5

In [71]:
(df['loss'].sum()*3000)/((df['days']*df['total_weight_out']).sum())

0.27944417302386343

In [1]:
import pandas as pd

In [3]:
df = pd.read_excel('Data-01.xlsx')

In [9]:
ar = df[['item','current_charge','interest_charge', 'weighted_charging']].to_numpy()
ar

array([['Chana', 2744.1568, 2981.069003733334, 2797.2000000000003],
       ['Chana', 1351.194, 1466.04549, 1377.0],
       ['Wheat', 3106.7633333333333, 3344.948522222222,
        3173.9999999999995],
       ...,
       ['Chana', 1617.4272, 1716.0902592, 1647.0],
       ['Chana', 1439.48, 1532.5663733333333, 1466.64],
       ['Chana', 1344.5159999999998, 1429.6686799999998, 1368.0]],
      dtype=object)

In [21]:
print(ar[ar[:,0]=='Chana'][:,1:].sum(axis=0))
print(ar[ar[:,0]=='Wheat'][:,1:].sum(axis=0))
print(ar[ar[:,0]=='Soyabean'][:,1:].sum(axis=0))

[638079.4867999998 684203.5603422666 650817.0]
[1024794.0206666657 1099465.348543556 1045403.3999999998]
[1001826.6519999999 1074051.481788444 1021797.5999999997]


In [17]:
ar[ar[:,0]=='Soyabean'][:,1:].sum(axis=0)

array([1001826.6519999999, 1074051.481788444, 1021797.5999999997],
      dtype=object)

In [18]:
ar[ar[:,0]=='Wheat'][:,1:].sum(axis=0)

array([1024794.0206666657, 1099465.348543556, 1045403.3999999998],
      dtype=object)